# Generated by Django 4.1.2 on 2022-10-31 03:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Issue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=254)),
                ("issue", models.TextField()),
                ("user_agent", models.CharField(max_length=200)),
                (
                    "date_posted",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
            ],
        ),
    ]
