# Generated by Django 4.1.3 on 2022-12-05 15:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Session",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date_posted",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("date", models.DateField(default=django.utils.timezone.now)),
                (
                    "timeblock",
                    models.CharField(
                        choices=[
                            ("A", "8:30-9:00"),
                            ("B", "9:00-9:30"),
                            ("C", "9:30-10:00"),
                            ("D", "10:00-10:30"),
                            ("E", "10:30-11:00"),
                            ("F", "11:00-11:30"),
                            ("G", "11:30-12:00"),
                            ("H", "12:00-12:30"),
                            ("I", "12:30-13:00"),
                            ("J", "13:00-13:30"),
                            ("K", "13:30-14:00"),
                            ("L", "14:00-14:30"),
                            ("M", "14:30-15:00"),
                            ("N", "15:00-15:30"),
                            ("O", "15:30-16:00"),
                            ("P", "16:00-16:30"),
                        ],
                        default="A",
                        max_length=1,
                    ),
                ),
                (
                    "location",
                    models.CharField(
                        choices=[("onsite", "Onsite"), ("online", "Online")],
                        default="onsite",
                        max_length=6,
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="student_session",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "teacher",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="teacher_session",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
