# Generated by Django 4.1.3 on 2022-12-28 21:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('scheduler', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('timeblock', models.CharField(max_length=6)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='studentSession', to=settings.AUTH_USER_MODEL)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacherSession', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Teacher Session',
                'verbose_name_plural': 'Teacher Sessions',
            },
        ),
    ]
